services:
  comfyui-worker:
    image: aykutmursalo/fffa:v5          # gerekirse yeni tag’i yaz
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      - SERVE_API_LOCALLY=true
      - HF_TOKEN=${HF_TOKEN}
      - CIVI_TOKEN=${CIVI_TOKEN}

    ports:
      - "8000:8000"
      - "8188:8188"

    volumes:
      - ./data/comfyui/output:/comfyui/output
      - ./data/runpod-volume:/runpod-volume